apiVersion: 1

datasources:
  - name: InfluxDB-k6
    uid: influxdb-k6
    type: influxdb
    access: proxy
    # url: http://k6-influxdb:8086
    url: http://host.docker.internal:8086
    database: k6
    isDefault: false
    editable: true
