apply plugin: 'org.springframework.boot'
apply plugin: 'jacoco'

dependencies {
	implementation project(':modules:domain')
	implementation project(':modules:infra-db')
	implementation project(':modules:common-web')
	implementation project(':modules:common-security')

	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'com.github.ben-manes.caffeine:caffeine'
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-mysql'
	runtimeOnly 'com.mysql:mysql-connector-j'
	testImplementation 'org.springframework.security:spring-security-test'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

	// httpClient 5
	implementation 'org.apache.httpcomponents.client5:httpclient5'

	// p6spy - SQL 로깅 (개발/테스트 전용)
	implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.2'
}


/**
 * Flyway가 infra 모듈의 db/migration 리소스를 확실히 인식하도록 설정
 */
tasks.named('processResources') {
	from(project(':modules:infra-db').sourceSets.main.resources.srcDirs) {
		include 'db/migration/**'
	}
}

jacoco {
	toolVersion = '0.8.10'
}

test {
	useJUnitPlatform()
	ignoreFailures = true
	finalizedBy(jacocoTestReport)
}

jacocoTestReport {
	dependsOn test
	reports {
		html.required = true
		xml.required = true
	}
	sourceDirectories.setFrom(files(sourceSets.main.allSource.srcDirs))
	classDirectories.setFrom(fileTree("$buildDir/classes/java/main") {
		exclude '**/generated/**'
	})
	executionData.setFrom(files("$buildDir/jacoco/test.exec"))
}
