apply plugin: 'java-library'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    api 'org.springframework.boot:spring-boot-starter-actuator'
    api 'io.micrometer:micrometer-registry-prometheus'
    api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6'
}
